name: verifplus_backoff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.134+134
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  file_picker: ^5.2.10
  cupertino_icons: ^1.0.2
  multi_dropdown: ^2.0.0
  package_info: ^2.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  jiffy: ^6.1.0
  auto_size_text: ^3.0.0
  group_radio_button: ^1.3.0
  easy_sidemenu: ^0.4.1
  cached_network_image: ^3.2.1
  pluto_menu_bar: ^2.0.0
  platform: ^3.1.0
  rflutter_alert: ^2.0.7
  custom_sliding_segmented_control: ^1.7.4
  flutter_map: ^7.0.1
  latlong2: ^0.9.1
  google_maps_flutter_web: ^0.4.0+9
  google_maps_flutter: ^2.2.8
  pointer_interceptor: ^0.9.3+4
  rnd: ^0.2.0
  geocode: 1.0.3
  provider: ^6.0.5
  dio: ^5.4.0
  flutter_riverpod: ^1.0.4
  davi: ^3.4.1
  flutter_typeahead: ^4.6.1
  intl: ^0.19.0
  uuid: ^4.1.0
  http: ^1.2.1
  flutter_polyline_points_plus: ^3.0.0
  google_geocoding_plus: ^1.0.0
  web: ^0.5.0
  google_fonts: ^6.2.1
  dropdown_button2: ^2.0.0
  syncfusion_flutter_pdfviewer: ^24.1.46
  syncfusion_flutter_core: ^24.1.46
  syncfusion_flutter_datepicker: ^24.1.46
  syncfusion_localizations: ^24.1.46
  syncfusion_flutter_calendar: ^24.1.46
  syncfusion_flutter_datagrid: ^24.1.46
  syncfusion_flutter_xlsio: ^24.1.46

  desktop_window: 0.4.0
  tab_container: ^3.0.0
  image: ^4.1.7
  desktop_drop: ^0.4.4
  aligned_dialog: ^0.0.7
  hand_signature: ^3.0.2
  csv: ^6.0.0

  flutter_spinkit: ^5.2.1
  fast_cached_network_image: ^1.2.9
  photo_view: ^0.15.0


dependency_overrides:
  pdf:
    path: ./pdf
  printing:
    path: ./printing

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
    - assets/fonts/OpenSans-Italic.ttf
    - assets/fonts/OpenSans-BoldItalic.ttf

