name: verifplus_backoff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.90+80
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  file_picker: ^5.2.10
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.9.2
  package_info: ^2.0.2
  uuid: ^3.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  csv: ^5.1.1
  http: ^0.13.5
  web: ^0.4.0
  jiffy: ^5.0.0
  google_fonts: ^3.0.1
  auto_size_text: ^3.0.0

  group_radio_button: ^1.3.0
  easy_sidemenu: ^0.4.1
  cached_network_image: ^3.2.1
  pluto_menu_bar: ^2.0.0
  platform: ^3.1.0
  syncfusion_flutter_pdfviewer: ^21.1.38
  rflutter_alert: ^2.0.7
  custom_sliding_segmented_control: ^1.7.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  google_maps_flutter_web: ^0.4.0+9
  google_maps_flutter: ^2.2.8
  pointer_interceptor: ^0.9.3+4
  rnd: ^0.2.0
  geocode: 1.0.3
  google_geocoding: ^0.2.0
  provider: ^6.0.5
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  davi: ^3.4.1
  flutter_typeahead: ^4.6.1
  intl: ^0.18.0
  syncfusion_flutter_core: ^21.2.10
  syncfusion_flutter_datepicker: ^21.2.10
  syncfusion_localizations: ^21.2.10
  syncfusion_flutter_calendar: ^21.2.10
  syncfusion_flutter_datagrid: ^21.2.10
  desktop_window: 0.4.0
  tab_container: ^2.0.0
  image: ^4.1.7
  desktop_drop: ^0.4.4
  aligned_dialog: ^0.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
